name: smallquery-glibc

on: [ push ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    container: quay.io/pypa/manylinux_2_24_x86_64

    steps:
    - uses: actions/checkout@v2

    - name: Hello
      run: |
        gcc --version