name: smallquery-package

on: [ push ]

jobs:
  build:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-10.15]

    steps:
    - uses: actions/checkout@v2

    - uses: actions/cache@v2
      name: Cache Build
      id: cache-build
      with:
        path: |
          ./build
          ~/.cache/bazel
        key: ${{ runner.os }}-build-v20220210-0

    - name: build wheel
      run: |
        mkdir -p ~/.cache/bazel
        make bazelisk
        make zetasql
        make wheel/${{ runner.os }}

    - uses: actions/upload-artifact@v2
      with:
        path: dist/*

  upload:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: artifact
          path: dist

      - uses: pypa/gh-action-pypi-publish@v1.4.2
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_TOKEN }}
          repository_url: https://test.pypi.org/legacy/