name: smallquery-package

on: [ push ]

jobs:
  build:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-10.15]

    steps:
    - uses: actions/checkout@v2

    - uses: actions/cache@v2
      name: Cache Build
      id: cache-build
      with:
        path: build
        key: ${{ runner.os }}-build-v20220209

    - name: test application
      run: |
        make bazelisk
        make zetasql
        make test
