name: smallquery-test

on: [ push ]

jobs:
  build:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]

    steps:
    - uses: actions/checkout@v2

    - uses: actions/cache@v2
      name: Cache Build
      id: cache-build
      with:
        path: build
        key: ${{ runner.os }}-build-v20220209-0

    - name: test application
      run: |
        make bazelisk
        make zetasql
        make test
