name: smallquery-test

on: [ push ]

jobs:
  build:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-10.15]

    steps:
    - uses: actions/checkout@v2

    - uses: actions/cache@v2
      name: Cache Bazel
      id: cache-bazel
      with:
        path: ~/.cache/bazel
        key: ${{ runner.os }}-bazel

    - uses: actions/cache@v2
      name: Cache Build
      id: cache-build
      with:
        path: build
        key: ${{ runner.os }}-build

    - name: test application
      run: |
        make bazelisk
        make zetasql
        make
        make test
