name: smallquery-test

on: [ push ]

jobs:
  build:
    name: Test
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - uses: actions/cache@v2
      name: Cache Bazel
      id: cache-bazel
      with:
        path: ~/.cache/bazel
        key: ${{ runner.os }}-bazel-v20220215-0

    - name: test application
      run: |
        make bazelisk
        make zetasql
        make test
