name: smallquery-test

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/cache@v2
      name: Cache Bazel
      id: cache-bazel
      with:
        path: ~/.cache/bazel
        key: ${{ runner.os }}-bazel

    - name: test application
      run: |
        make bazelisk
        make zetasql
        make
        make test
