name: smallquery-test

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: test application
      run: |
        make bazelisk
        make zetasql
        make
        make test
