# ref. https://github.com/msgpack/msgpack-python/blob/89ea57747ebcb0fad004a92ab00ebf13c10b2d51/.github/workflows/wheel.yml
name: Build Wheels
on: [ push ]

jobs:
  build_wheels:
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2022, macos-10.15]
    runs-on: ${{ matrix.os }}
    name: Build wheels on ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v1
        with:
          platforms: arm64

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          cache: "pip"

      - name: Build
        uses: pypa/cibuildwheel@v2.2.2
        env:
          CIBW_BEFORE_ALL: |
            apt install -y gcc g++
            python3 tools/ci/bazelisk.py --version
            make zetasql
          CIBW_ARCHS_LINUX: auto aarch64
          CIBW_ARCHS_MACOS: x86_64 universal2 arm64
          CIBW_SKIP: pp*

      - name: Upload Wheels
        uses: actions/upload-artifact@v1
        with:
          name: Wheels
          path: wheelhouse