name: Build

on: [push]

jobs:
  build_wheels:
    name: Build wheels
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        name: Cache Build
        id: cache-build
        with:
          path: |
            ./build
            ~/.cache/bazel
          key: ${{ runner.os }}-bazel-v20220215-2

      - uses: actions/setup-python@v2

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.3.1

      - name: Build wheels
        run: |
          CIBUILDWHEEL_BAZEL_CACHE=/host/$HOME/.cache/bazel python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BEFORE_ALL: make zetasql wheel

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl